server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/house
mybatis:
  type-aliases-package: kr.co.deco.house.entity
  mapper-locations: classpath:mappers/**/*.xml

social:
  app:
    kakao:
      client-id: 46bd758cb8caf1c4edc4549db3094436
      redirect_uri: http://localhost:8080/auth/kakao
    naver:
      client-id: 5GV6LNs1bbuTsXojYY5Y
      client-secret: 8i7GJ93uLo
      redirect-uri: http://localhost:8080/auth/naver
    micro-soft:
      client-id: aa37dd07-47bc-4942-a172-7a50666bb9e6
      client-secret: zJq8Q~9tKc0TLUUEXy7YkeWID1yJOOvcH18o3bFd
      redirect-uri: http://localhost:8080/auth/ms